### ISSUE TITLE
tmole.exe shows no output in cmd 

### ISSUE THREAD

**Issue by sccpsteve** [robbie-cahill/tunnelmole-client#2] opened 2023-03-06 05:29 UTC
Upon cding into tmole.exe and attempting to get a random public URL forwarding to a specific port, after I press the enter key, the text cursor leaves focus and no output shows. Re-entering the command leads to the same result. See attached image below for more information.

tmole version: 1.0
Windows 11 
Command Prompt (administrator)
Installed via Github/npm 

![image](https://user-images.githubusercontent.com/101025513/223025650-9addb2ff-7ee4-4a52-ad80-357060b07dd1.png)

**Expectation:**
tmole.exe is supposed to send outputs in the console after the enter key is pressed, this information includes critical information for port forwarding. 

**Reality: **
tmole.exe shows no outputs upon pressing the enter key whatsoever, leaves command bar focus and does nothing.

**Troubleshooting:**
- I tried running cmd through admin. 
- I tried various different ports.
- I tried other commands of tmole, those showed up properly.
- I tried resetting all network adapters. 
- I tried reinstalling the software. 

I asked a friend to attempt to reproduce the issue, and he was unable to reproduce the bug as he was able to port-forward successfully, so what am I doing wrong here? It should be easier to operate the software than this. Any assistance and/or bug fixes would be appreciated.

**Comment by robbie-cahill** [comment] 2023-03-06 06:30
Sounds like a duplicate of #2. 

What if you try with Windows Firewall turned off?

Are you behind any kind of corporate network or firewall or are you trying this from home?

**Comment by sccpsteve** [comment] 2023-03-06 19:26
I'm trying to use the software from home. I turned Windows Firewall off to no avail. Is there anything else I should try?

**Comment by robbie-cahill** [comment] 2023-03-07 10:44
Sounds like some kind of external network related problem.

I've just published a new version with optional debug logging. Can you download it again to update then run `tmole` like below and paste the output?

`tmole 15 --debug`

**Comment by sccpsteve** [comment] 2023-03-07 21:08
Hmm, nothing's changed. It shows this in the console and just completely stops.
```
C:\Users\sccps\Downloads>tmole 25 --debug
Sending initialise message
```

**Comment by robbie-cahill** [comment] 2023-03-09 07:26
Could you leave it running for about 10 minutes and see if it prints out any other errors and paste them in here?

I'm wondering if there is something going on with your ISP. Does it work if you try it from a different internet connection or over a VPN? Which internet provider are you using?

**Comment by robbie-cahill** [comment] 2023-03-09 09:47
After updating some config on the server this seems to be fixed for me, can you confirm?

**Comment by sccpsteve** [comment] 2023-03-09 19:32
It's fixed for me. Yay! 
```C:\Users\sccps\Downloads>tmole 235
http://13i4yb-ip-64-190-226-190.tunnelmole.com is forwarding to localhost:235
https://13i4yb-ip-64-190-226-190.tunnelmole.com is forwarding to localhost:235```

**Comment by sccpsteve** [comment] 2023-03-09 19:35
It's fixed! Woohoo! 
```
C:\Users\sccps\Downloads>tmole 235
http://13i4yb-ip-[MY IP ADDRESS].tunnelmole.com is forwarding to localhost:235
https://13i4yb-ip-[MY IP ADDRESS].tunnelmole.com is forwarding to localhost:235

**Closed** 2023-03-10 09:37 UTC
